
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'client-api'
    static_configs:
      - targets: ['client-api:8081']
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 10s
    basic_auth:
      username: 'prometheus'
      password: 'monitoring'